/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.servidor;

import classes.Usuarios;

/**
 *
 * @author isaac
 */
public class Navigation extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosView
     */
    private Usuarios user;
    
    public Navigation() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuariosButton.setEnabled(false);
        this.clientesButton.setEnabled(false);
        this.productosButton.setEnabled(false);
        this.ventasButton.setEnabled(false);
    }
    
        public void setNavigation(String rol) {
            switch (rol) {
                case "admin":
                    this.usuariosButton.setEnabled(true);
                    this.clientesButton.setEnabled(true);
                    this.productosButton.setEnabled(true);
                    this.ventasButton.setEnabled(true);
                    break;
                case "cajero":
                    this.clientesButton.setEnabled(true);
                    this.ventasButton.setEnabled(true);
                    break;
                case "supervisor":
                    this.usuariosButton.setEnabled(true);
                    this.productosButton.setEnabled(true);
                    break;
                default:
                    break;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productosButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clientesButton = new javax.swing.JButton();
        usuariosButton = new javax.swing.JButton();
        ventasButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosButton.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        productosButton.setText("Productos");
        productosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(productosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/whiteLogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 160));

        clientesButton.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        clientesButton.setText("Clientes");
        clientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clientesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, 50));

        usuariosButton.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        usuariosButton.setText("Usuarios");
        usuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(usuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 50));

        ventasButton.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        ventasButton.setText("Ventas");
        ventasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ventasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 50));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenido!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-dblue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosButtonActionPerformed
        ProductosView products = new ProductosView();
        products.show();
    }//GEN-LAST:event_productosButtonActionPerformed

    private void clientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButtonActionPerformed
        ClientesView clients = new ClientesView();
        clients.show();
    }//GEN-LAST:event_clientesButtonActionPerformed

    private void usuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosButtonActionPerformed
        UsuariosView users = new UsuariosView();
        users.show();
    }//GEN-LAST:event_usuariosButtonActionPerformed

    private void ventasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasButtonActionPerformed
        VentasView ventas = new VentasView();
        ventas.show();
    }//GEN-LAST:event_ventasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton productosButton;
    private javax.swing.JButton usuariosButton;
    private javax.swing.JButton ventasButton;
    // End of variables declaration//GEN-END:variables
}
